<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>explorer_ws_tests</name>
  <version>0.0.0</version>
  <description>Test package for explorer_ws (integration / launch tests)</description>
  <maintainer email="corentin.ducatez@orthopus.com">Corentin Ducatez</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>explorer_on_wheelchair</test_depend>
  <test_depend>explorer_bringup</test_depend>
  <test_depend>explorer_user_interfaces_cpp</test_depend>
  <test_depend>qontrol_controller</test_depend>
  <test_depend>gripper_pincette</test_depend>
  <test_depend>explorer_input_devices</test_depend>
  <test_depend>explorer_user_interfaces_web</test_depend>
  <test_depend>explorer_controllers</test_depend>
  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>ament_index_python</test_depend>
  <test_depend>launch</test_depend>
  <test_depend>launch_ros</test_depend>
  <test_depend>launch_testing_ament_cmake</test_depend>
  <test_depend>launch_testing_ros</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
