name: Build docker images (CI / dev / prod)
on:
    push:
      tags:
          - '**'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-CI-docker-image:
    ## Deploy new CI image only if master changes
    if: ${{ github.ref == 'master' }}
    uses: ./.github/workflows/workflow-docker-image.yml
    with:
      image_name: builder
      target: explorer_ws_builder
    secrets: inherit

  build-and-push-dev-docker-image:
    uses: ./.github/workflows/workflow-docker-image.yml
    with:
      image_name: dev
      target: explorer_ws_dev
    secrets: inherit

  pull-private-repositories:
    uses: ./.github/workflows/workflow-pull-private-repositories.yml
    secrets: inherit

  build-and-push-prod-docker-image:
    needs: pull-private-repositories
    uses: ./.github/workflows/workflow-docker-image.yml
    with:
      image_name: prod
      target: explorer_ws_prod
      artifact_name: pull-private-repositories-explorer-ws
    secrets: inherit